version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: worldcup_postgres
    environment:
      POSTGRES_DB: worldcup_db
      POSTGRES_USER: wc_user
      POSTGRES_PASSWORD: wc_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: worldcup_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: worldcup_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@worldcup.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: